<?php
/**
 * 默认模块注册表。
 *
 * 这里作为模块系统的单一清单来源，新增/调整默认模块时优先修改本文件，
 * 避免继续在 Module_Manager 里维护超长的 register_module() 调用串。
 * 单个条目既可以直接写模块类名，也可以写成包含 class / group / ai_enabled / keywords 的数组。
 * v2 元数据可继续声明 industry_tags / page_tags / intent_tags / content_models / schema_types / ai_hints，
 * 未声明的字段会由 Module_Standards 基于模块 ID、分组和描述自动推断。
 *
 * @package Developer_Starter
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
    'core' => array(
        array(
            'class'          => \Developer_Starter\Modules\Modules\Banner_Module::class,
            'keywords'       => array( 'hero', 'banner', '首屏', '首页', '落地页' ),
            'industry_tags'  => array( 'general', 'enterprise', 'technology', 'b2b' ),
            'page_tags'      => array( 'home', 'landing' ),
            'intent_tags'    => array( 'hero', 'conversion', 'storytelling' ),
            'content_models' => array( 'page' ),
            'schema_types'   => array( 'WebSite', 'Organization' ),
            'ai_hints'       => array(
                'summary'             => '用于页面首屏，适合承载品牌主张、核心卖点和主 CTA。',
                'content_guidance'    => '优先生成一句清晰主标题、一段可信副标题和一个明确行动按钮。',
                'conversion_guidance' => '按钮应指向咨询、了解方案、查看产品或预约等主转化动作。',
            ),
        ),
        array(
            'class'          => \Developer_Starter\Modules\Modules\Services_Module::class,
            'keywords'       => array( 'services', '服务', '能力', '业务' ),
            'industry_tags'  => array( 'general', 'enterprise', 'b2b', 'local_service' ),
            'page_tags'      => array( 'home', 'services' ),
            'intent_tags'    => array( 'listing', 'conversion', 'education' ),
            'content_models' => array( 'service' ),
            'schema_types'   => array( 'Service', 'ItemList' ),
            'ai_hints'       => array(
                'summary'          => '用于展示服务项目、解决方案或业务范围。',
                'content_guidance' => '每个服务项应包含短标题、直接收益和可理解的图标/图片线索。',
            ),
        ),
        array(
            'class'          => \Developer_Starter\Modules\Modules\Features_Module::class,
            'keywords'       => array( 'features', '特点', '优势', '卖点' ),
            'industry_tags'  => array( 'general', 'enterprise', 'technology', 'software' ),
            'page_tags'      => array( 'home', 'services', 'products' ),
            'intent_tags'    => array( 'content', 'conversion', 'proof' ),
            'content_models' => array( 'service', 'product' ),
            'schema_types'   => array( 'Service', 'Product' ),
        ),
        \Developer_Starter\Modules\Modules\Clients_Module::class,
        \Developer_Starter\Modules\Modules\Stats_Module::class,
        \Developer_Starter\Modules\Modules\CTA_Module::class,
        \Developer_Starter\Modules\Modules\Image_Text_Module::class,
        \Developer_Starter\Modules\Modules\Columns_Module::class,
        \Developer_Starter\Modules\Modules\Timeline_Module::class,
        array(
            'class'          => \Developer_Starter\Modules\Modules\FAQ_Module::class,
            'keywords'       => array( 'faq', '问答', '常见问题', '支持' ),
            'industry_tags'  => array( 'general', 'enterprise', 'saas', 'education', 'local_service' ),
            'page_tags'      => array( 'faq', 'services', 'products' ),
            'intent_tags'    => array( 'support', 'trust', 'conversion' ),
            'content_models' => array( 'faq' ),
            'schema_types'   => array( 'FAQPage' ),
        ),
        array(
            'class'          => \Developer_Starter\Modules\Modules\Contact_Module::class,
            'keywords'       => array( 'contact', '联系', '表单', '预约', '线索' ),
            'industry_tags'  => array( 'general', 'enterprise', 'local_service', 'b2b' ),
            'page_tags'      => array( 'contact', 'booking', 'landing' ),
            'intent_tags'    => array( 'lead_capture', 'conversion' ),
            'content_models' => array( 'branch' ),
            'schema_types'   => array( 'Organization', 'LocalBusiness' ),
            'ai_hints'       => array(
                'summary'             => '用于收集咨询、预约、报价或商务合作线索。',
                'conversion_guidance' => '文案要明确下一步动作，并降低用户提交表单的心理成本。',
            ),
        ),
        \Developer_Starter\Modules\Modules\News_Module::class,
        array(
            'class'          => \Developer_Starter\Modules\Modules\Products_Module::class,
            'keywords'       => array( 'products', '产品', '商品', '目录' ),
            'industry_tags'  => array( 'general', 'enterprise', 'manufacturing', 'ecommerce', 'b2b' ),
            'page_tags'      => array( 'home', 'products' ),
            'intent_tags'    => array( 'commerce', 'listing', 'conversion' ),
            'content_models' => array( 'product' ),
            'schema_types'   => array( 'Product', 'ItemList' ),
        ),
        \Developer_Starter\Modules\Modules\Work_Library_Module::class,
        \Developer_Starter\Modules\Modules\Work_Detail_Module::class,
        array(
            'class'          => \Developer_Starter\Modules\Modules\Cases_Module::class,
            'keywords'       => array( 'cases', '案例', '客户案例', '项目' ),
            'industry_tags'  => array( 'general', 'enterprise', 'b2b', 'technology', 'local_service' ),
            'page_tags'      => array( 'home', 'cases' ),
            'intent_tags'    => array( 'proof', 'trust', 'storytelling' ),
            'content_models' => array( 'case' ),
            'schema_types'   => array( 'Article', 'CollectionPage' ),
        ),
        \Developer_Starter\Modules\Modules\Downloads_Module::class,
        \Developer_Starter\Modules\Modules\Process_Module::class,
        array(
            'class'          => \Developer_Starter\Modules\Modules\Pricing_Module::class,
            'keywords'       => array( 'pricing', '价格', '套餐', '报价' ),
            'industry_tags'  => array( 'general', 'saas', 'software', 'education', 'local_service' ),
            'page_tags'      => array( 'pricing', 'landing', 'products' ),
            'intent_tags'    => array( 'pricing', 'comparison', 'conversion' ),
            'content_models' => array( 'product', 'service' ),
            'schema_types'   => array( 'Product', 'Service' ),
        ),
        \Developer_Starter\Modules\Modules\Video_Module::class,
        \Developer_Starter\Modules\Modules\Testimonials_Module::class,
        \Developer_Starter\Modules\Modules\Countdown_Module::class,
        \Developer_Starter\Modules\Modules\Multi_Image_Text_Module::class,
        \Developer_Starter\Modules\Modules\Features_List_Module::class,
        \Developer_Starter\Modules\Modules\Team_Module::class,
        \Developer_Starter\Modules\Modules\Gallery_Module::class,
        \Developer_Starter\Modules\Modules\Certificate_Honors_Module::class,
        \Developer_Starter\Modules\Modules\Compliance_Trust_Module::class,
        \Developer_Starter\Modules\Modules\Branches_Module::class,
        \Developer_Starter\Modules\Modules\Tabs_Module::class,
        \Developer_Starter\Modules\Modules\Visual_Tabs_Module::class,
        \Developer_Starter\Modules\Modules\Accordion_Module::class,
        \Developer_Starter\Modules\Modules\Comparison_Module::class,
        \Developer_Starter\Modules\Modules\Image_Comparison_Module::class,
        \Developer_Starter\Modules\Modules\Chart_Module::class,
        array(
            'class'          => \Developer_Starter\Modules\Modules\Blog_Module::class,
            'keywords'       => array( 'blog', '博客', '杂志', '资讯', '文章' ),
            'industry_tags'  => array( 'general', 'blog', 'magazine', 'media', 'enterprise' ),
            'page_tags'      => array( 'blog', 'news', 'resource', 'home' ),
            'intent_tags'    => array( 'content', 'listing', 'media' ),
            'content_models' => array( 'post', 'author' ),
            'schema_types'   => array( 'BlogPosting', 'Article', 'CollectionPage' ),
        ),
        array(
            'class'          => \Developer_Starter\Modules\Modules\Query_Loop_Module::class,
            'keywords'       => array( 'query loop', 'loop', 'archive', '查询循环', '归档查询', '文章列表', '内容模型' ),
            'industry_tags'  => array( 'general', 'blog', 'magazine', 'enterprise', 'local_service' ),
            'page_tags'      => array( 'archive', 'blog', 'news', 'resource', 'search', 'category', 'tag' ),
            'intent_tags'    => array( 'content', 'listing', 'navigation' ),
            'content_models' => array( 'post', 'case', 'service', 'team', 'resource', 'branch' ),
            'schema_types'   => array( 'CollectionPage', 'ItemList', 'BlogPosting', 'Article' ),
            'ai_hints'       => array(
                'summary' => '用于主题模板和归档页，按当前查询、分类标签、文章类型或启灵内容模型输出列表。',
            ),
        ),
        \Developer_Starter\Modules\Modules\Featured_Posts_Module::class,
        \Developer_Starter\Modules\Modules\Breaking_News_Ticker_Module::class,
        \Developer_Starter\Modules\Modules\Author_Matrix_Module::class,
        \Developer_Starter\Modules\Modules\About_Me_Card_Module::class,
        \Developer_Starter\Modules\Modules\Friendly_Links_Module::class,
        \Developer_Starter\Modules\Modules\Media_List_Module::class,
        \Developer_Starter\Modules\Modules\Micro_Journal_Stream_Module::class,
        \Developer_Starter\Modules\Modules\Reader_Wall_Module::class,
        \Developer_Starter\Modules\Modules\Knowledge_Cards_Module::class,
        \Developer_Starter\Modules\Modules\Double_Column_Carousel_Module::class,
        \Developer_Starter\Modules\Modules\Product_Showcase_Module::class,
        \Developer_Starter\Modules\Modules\Hero_Search_Module::class,
        \Developer_Starter\Modules\Modules\Service_Cards_Module::class,
    ),
    'component' => array(
        array(
            'class'          => \Developer_Starter\Modules\Modules\Magic_Layout_Module::class,
            'ai_enabled'     => false,
            'keywords'       => array( 'magic layout', 'free layout', 'container', 'columns', 'elements', '魔方布局', '自由布局', '分栏' ),
            'industry_tags'  => array( 'general', 'enterprise', 'technology', 'blog', 'magazine', 'personal' ),
            'page_tags'      => array( 'section', 'home', 'landing', 'blog', 'detail' ),
            'intent_tags'    => array( 'content', 'storytelling', 'conversion' ),
            'content_models' => array( 'page' ),
            'ai_hints'       => array(
                'summary' => '自由容器与分栏布局模块，适合构建非标准版式。',
            ),
        ),
    ),
    'footer' => array(
        array(
            'class'          => \Developer_Starter\Modules\Modules\Footer_Suite_Module::class,
            'keywords'       => array( 'footer', '页脚', '底部', '友情链接', '备案', '版权', '二维码' ),
            'industry_tags'  => array( 'general', 'enterprise', 'b2b', 'local_service', 'ecommerce', 'technology' ),
            'page_tags'      => array( 'footer', 'home', 'site' ),
            'intent_tags'    => array( 'navigation', 'trust', 'contact', 'compliance' ),
            'content_models' => array( 'page' ),
            'schema_types'   => array( 'Organization', 'WebSite' ),
            'ai_hints'       => array(
                'summary'          => '用于替换整页脚，整合品牌、链接、联系、二维码、友链和备案。',
                'content_guidance' => '优先保留站点已有页脚信息，再按页面定位补充必要链接和联系入口。',
            ),
        ),
    ),
    'software' => array(
        \Developer_Starter\Modules\Modules\Software_Carousel_Module::class,
        \Developer_Starter\Modules\Modules\Software_Category_Module::class,
        \Developer_Starter\Modules\Modules\Software_Ranking_Module::class,
        array(
            'class'          => \Developer_Starter\Modules\Modules\GitHub_Activity_Module::class,
            'keywords'       => array( 'github', 'repo', 'repository', '开源', '仓库', 'stars', 'forks', 'release', 'commit' ),
            'industry_tags'  => array( 'software', 'technology', 'opensource' ),
            'page_tags'      => array( 'landing', 'products', 'resource' ),
            'intent_tags'    => array( 'proof', 'community', 'updates' ),
            'content_models' => array( 'page' ),
            'ai_hints'       => array(
                'summary' => '用于开源项目和开发工具官网，自动展示公开 GitHub 仓库的社区数据、最新版本和提交动态。',
            ),
        ),
    ),
    'resume' => array(
        \Developer_Starter\Modules\Modules\Resume_Hero_Module::class,
        \Developer_Starter\Modules\Modules\Skills_Module::class,
        \Developer_Starter\Modules\Modules\Experience_Timeline_Module::class,
    ),
    'qiling' => array(
        \Developer_Starter\Modules\Modules\Qiling_Image_Guide_Module::class,
        \Developer_Starter\Modules\Modules\Category_Tabs_Module::class,
        \Developer_Starter\Modules\Modules\Resource_Stats_Module::class,
        \Developer_Starter\Modules\Modules\Qiling_Universal_Recommend_Module::class,
        \Developer_Starter\Modules\Modules\Dynamic_Banner_Module::class,
        \Developer_Starter\Modules\Modules\Brand_Banner_Pro_Module::class,
        \Developer_Starter\Modules\Modules\Resource_Hero_Pro_Module::class,
        \Developer_Starter\Modules\Modules\App_Hero_Module::class,
        \Developer_Starter\Modules\Modules\Tabbed_Carousel_Module::class,
        \Developer_Starter\Modules\Modules\Fullscreen_Video_Module::class,
        \Developer_Starter\Modules\Modules\Circle_Wheel_Module::class,
        \Developer_Starter\Modules\Modules\Interact_Hero_Module::class,
        \Developer_Starter\Modules\Modules\Main_Category_Content_Module::class,
        \Developer_Starter\Modules\Modules\Video_Portal_Hero_Module::class,
        \Developer_Starter\Modules\Modules\Video_Ranking_Module::class,
        \Developer_Starter\Modules\Modules\Qiling_Shop_Showcase_Module::class,
    ),
    'industry' => array(
        \Developer_Starter\Modules\Modules\Menu_Module::class,
        \Developer_Starter\Modules\Modules\Curriculum_Module::class,
        \Developer_Starter\Modules\Modules\Pet_Profile_Module::class,
        \Developer_Starter\Modules\Modules\Lookbook_Module::class,
        \Developer_Starter\Modules\Modules\Promotion_Module::class,
        \Developer_Starter\Modules\Modules\Tour_Package_Module::class,
        \Developer_Starter\Modules\Modules\Itinerary_Module::class,
        \Developer_Starter\Modules\Modules\Ticket_Showcase_Module::class,
        \Developer_Starter\Modules\Modules\Room_Showcase_Module::class,
        \Developer_Starter\Modules\Modules\Hotel_Amenities_Module::class,
        \Developer_Starter\Modules\Modules\Booking_Entry_Module::class,
    ),
);
