<?php
/**
 * Data config for component style definitions.
 *
 * @package Developer_Starter
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
            array( 'key' => 'button_bg', 'cssVar' => '--qiling-component-button-bg', 'group' => 'button', 'label' => __( '按钮背景', 'developer-starter' ) ),
            array( 'key' => 'button_text', 'cssVar' => '--qiling-component-button-text', 'group' => 'button', 'label' => __( '按钮文字', 'developer-starter' ) ),
            array( 'key' => 'button_border', 'cssVar' => '--qiling-component-button-border', 'group' => 'button', 'label' => __( '按钮边框', 'developer-starter' ) ),
            array( 'key' => 'button_hover_bg', 'cssVar' => '--qiling-component-button-hover-bg', 'group' => 'button', 'label' => __( '按钮悬停背景', 'developer-starter' ) ),
            array( 'key' => 'button_hover_text', 'cssVar' => '--qiling-component-button-hover-text', 'group' => 'button', 'label' => __( '按钮悬停文字', 'developer-starter' ) ),
            array( 'key' => 'button_shadow', 'cssVar' => '--qiling-component-button-shadow', 'group' => 'button', 'label' => __( '按钮阴影', 'developer-starter' ) ),
            array( 'key' => 'button_padding', 'cssVar' => '--qiling-component-button-padding', 'group' => 'button', 'label' => __( '按钮内边距', 'developer-starter' ) ),
            array( 'key' => 'button_secondary_bg', 'cssVar' => '--qiling-component-button-secondary-bg', 'group' => 'button_secondary', 'label' => __( '次要按钮背景', 'developer-starter' ) ),
            array( 'key' => 'button_secondary_text', 'cssVar' => '--qiling-component-button-secondary-text', 'group' => 'button_secondary', 'label' => __( '次要按钮文字', 'developer-starter' ) ),
            array( 'key' => 'button_secondary_border', 'cssVar' => '--qiling-component-button-secondary-border', 'group' => 'button_secondary', 'label' => __( '次要按钮边框', 'developer-starter' ) ),
            array( 'key' => 'button_secondary_hover_bg', 'cssVar' => '--qiling-component-button-secondary-hover-bg', 'group' => 'button_secondary', 'label' => __( '次要按钮悬停背景', 'developer-starter' ) ),
            array( 'key' => 'border_accent', 'cssVar' => '--qiling-component-border-accent', 'group' => 'border', 'label' => __( '强调边框', 'developer-starter' ) ),
            array( 'key' => 'heading_weight', 'cssVar' => '--qiling-component-heading-weight', 'group' => 'heading', 'label' => __( '标题字重', 'developer-starter' ) ),
            array( 'key' => 'heading_letter_spacing', 'cssVar' => '--qiling-component-heading-letter-spacing', 'group' => 'heading', 'label' => __( '标题字间距', 'developer-starter' ) ),
            array( 'key' => 'card_bg', 'cssVar' => '--qiling-component-card-bg', 'group' => 'card', 'label' => __( '卡片背景', 'developer-starter' ) ),
            array( 'key' => 'card_border', 'cssVar' => '--qiling-component-card-border', 'group' => 'card', 'label' => __( '卡片边框', 'developer-starter' ) ),
            array( 'key' => 'card_shadow', 'cssVar' => '--qiling-component-card-shadow', 'group' => 'card', 'label' => __( '卡片阴影', 'developer-starter' ) ),
            array( 'key' => 'title_bar_bg', 'cssVar' => '--qiling-component-title-bar-bg', 'group' => 'module_surface', 'label' => __( '标题条背景', 'developer-starter' ) ),
            array( 'key' => 'title_bar_text', 'cssVar' => '--qiling-component-title-bar-text', 'group' => 'module_surface', 'label' => __( '标题条文字', 'developer-starter' ) ),
            array( 'key' => 'title_bar_border', 'cssVar' => '--qiling-component-title-bar-border', 'group' => 'module_surface', 'label' => __( '标题条边框', 'developer-starter' ) ),
            array( 'key' => 'list_header_bg', 'cssVar' => '--qiling-component-list-header-bg', 'group' => 'module_surface', 'label' => __( '列表表头背景', 'developer-starter' ) ),
            array( 'key' => 'list_header_text', 'cssVar' => '--qiling-component-list-header-text', 'group' => 'module_surface', 'label' => __( '列表表头文字', 'developer-starter' ) ),
            array( 'key' => 'list_header_border', 'cssVar' => '--qiling-component-list-header-border', 'group' => 'module_surface', 'label' => __( '列表表头边框', 'developer-starter' ) ),
            array( 'key' => 'highlight_bg', 'cssVar' => '--qiling-component-highlight-bg', 'group' => 'module_surface', 'label' => __( '高亮块背景', 'developer-starter' ) ),
            array( 'key' => 'highlight_text', 'cssVar' => '--qiling-component-highlight-text', 'group' => 'module_surface', 'label' => __( '高亮块文字', 'developer-starter' ) ),
            array( 'key' => 'highlight_border', 'cssVar' => '--qiling-component-highlight-border', 'group' => 'module_surface', 'label' => __( '高亮块边框', 'developer-starter' ) ),
            array( 'key' => 'highlight_soft_bg', 'cssVar' => '--qiling-component-highlight-soft-bg', 'group' => 'module_surface', 'label' => __( '高亮弱背景', 'developer-starter' ) ),
            array( 'key' => 'form_input_bg', 'cssVar' => '--qiling-component-form-input-bg', 'group' => 'form', 'label' => __( '输入框背景', 'developer-starter' ) ),
            array( 'key' => 'form_input_text', 'cssVar' => '--qiling-component-form-input-text', 'group' => 'form', 'label' => __( '输入框文字', 'developer-starter' ) ),
            array( 'key' => 'form_input_border', 'cssVar' => '--qiling-component-form-input-border', 'group' => 'form', 'label' => __( '输入框边框', 'developer-starter' ) ),
            array( 'key' => 'form_focus_border', 'cssVar' => '--qiling-component-form-focus-border', 'group' => 'form', 'label' => __( '输入框聚焦边框', 'developer-starter' ) ),
            array( 'key' => 'auth_action_bg', 'cssVar' => '--qiling-component-auth-action-bg', 'group' => 'auth', 'label' => __( '认证主按钮背景', 'developer-starter' ) ),
            array( 'key' => 'auth_action_text', 'cssVar' => '--qiling-component-auth-action-text', 'group' => 'auth', 'label' => __( '认证主按钮文字', 'developer-starter' ) ),
            array( 'key' => 'auth_code_bg', 'cssVar' => '--qiling-component-auth-code-bg', 'group' => 'auth', 'label' => __( '验证码按钮背景', 'developer-starter' ) ),
            array( 'key' => 'auth_code_text', 'cssVar' => '--qiling-component-auth-code-text', 'group' => 'auth', 'label' => __( '验证码按钮文字', 'developer-starter' ) ),
            array( 'key' => 'auth_slider_track_bg', 'cssVar' => '--qiling-component-auth-slider-track-bg', 'group' => 'auth', 'label' => __( '滑动轨道背景', 'developer-starter' ) ),
            array( 'key' => 'auth_slider_handle_bg', 'cssVar' => '--qiling-component-auth-slider-handle-bg', 'group' => 'auth', 'label' => __( '滑块按钮背景', 'developer-starter' ) ),
            array( 'key' => 'auth_slider_progress_bg', 'cssVar' => '--qiling-component-auth-slider-progress-bg', 'group' => 'auth', 'label' => __( '滑动进度背景', 'developer-starter' ) ),
            array( 'key' => 'auth_verified_color', 'cssVar' => '--qiling-component-auth-verified-color', 'group' => 'auth', 'label' => __( '验证成功颜色', 'developer-starter' ) ),
            array( 'key' => 'module_title_color', 'cssVar' => '--qiling-component-module-title-color', 'group' => 'module_title', 'label' => __( '模块标题颜色', 'developer-starter' ) ),
            array( 'key' => 'module_title_size', 'cssVar' => '--qiling-component-module-title-size', 'group' => 'module_title', 'label' => __( '模块标题字号', 'developer-starter' ) ),
            array( 'key' => 'module_title_align', 'cssVar' => '--qiling-component-module-title-align', 'group' => 'module_title', 'label' => __( '模块标题对齐', 'developer-starter' ) ),
            array( 'key' => 'post_card_bg', 'cssVar' => '--qiling-component-post-card-bg', 'group' => 'post_card', 'label' => __( '文章卡片背景', 'developer-starter' ) ),
            array( 'key' => 'post_card_border', 'cssVar' => '--qiling-component-post-card-border', 'group' => 'post_card', 'label' => __( '文章卡片边框', 'developer-starter' ) ),
            array( 'key' => 'post_card_shadow', 'cssVar' => '--qiling-component-post-card-shadow', 'group' => 'post_card', 'label' => __( '文章卡片阴影', 'developer-starter' ) ),
            array( 'key' => 'post_card_title_color', 'cssVar' => '--qiling-component-post-card-title-color', 'group' => 'post_card', 'label' => __( '文章卡片标题颜色', 'developer-starter' ) ),
            array( 'key' => 'post_card_meta_color', 'cssVar' => '--qiling-component-post-card-meta-color', 'group' => 'post_card', 'label' => __( '文章卡片元信息颜色', 'developer-starter' ) ),
            array( 'key' => 'header_bg', 'cssVar' => '--qiling-component-header-bg', 'group' => 'header', 'label' => __( '页头背景', 'developer-starter' ) ),
            array( 'key' => 'header_border', 'cssVar' => '--qiling-component-header-border', 'group' => 'header', 'label' => __( '页头边框', 'developer-starter' ) ),
            array( 'key' => 'header_shadow', 'cssVar' => '--qiling-component-header-shadow', 'group' => 'header', 'label' => __( '页头阴影', 'developer-starter' ) ),
            array( 'key' => 'header_text', 'cssVar' => '--qiling-component-header-text', 'group' => 'header', 'label' => __( '页头文字', 'developer-starter' ) ),
            array( 'key' => 'header_scrolled_text', 'cssVar' => '--qiling-component-header-scrolled-text', 'group' => 'header', 'label' => __( '滚动后页头文字', 'developer-starter' ) ),
            array( 'key' => 'header_logo_transparent_fill', 'cssVar' => '--qiling-component-header-logo-transparent-fill', 'group' => 'header', 'label' => __( '透明头部文字 Logo 背景', 'developer-starter' ) ),
            array( 'key' => 'header_logo_scrolled_fill', 'cssVar' => '--qiling-component-header-logo-scrolled-fill', 'group' => 'header', 'label' => __( '滚动/内页文字 Logo 背景', 'developer-starter' ) ),
            array( 'key' => 'header_phone_bg', 'cssVar' => '--qiling-component-header-phone-bg', 'group' => 'header', 'label' => __( '页头电话按钮背景', 'developer-starter' ) ),
            array( 'key' => 'header_phone_text', 'cssVar' => '--qiling-component-header-phone-text', 'group' => 'header', 'label' => __( '页头电话按钮文字', 'developer-starter' ) ),
            array( 'key' => 'header_phone_transparent_bg', 'cssVar' => '--qiling-component-header-phone-transparent-bg', 'group' => 'header', 'label' => __( '透明头部电话按钮背景', 'developer-starter' ) ),
            array( 'key' => 'header_phone_transparent_text', 'cssVar' => '--qiling-component-header-phone-transparent-text', 'group' => 'header', 'label' => __( '透明头部电话按钮文字', 'developer-starter' ) ),
            array( 'key' => 'nav_link', 'cssVar' => '--qiling-component-nav-link', 'group' => 'desktop_nav', 'label' => __( '桌面导航文字', 'developer-starter' ) ),
            array( 'key' => 'nav_scrolled_link', 'cssVar' => '--qiling-component-nav-scrolled-link', 'group' => 'desktop_nav', 'label' => __( '滚动后桌面导航文字', 'developer-starter' ) ),
            array( 'key' => 'nav_hover_bg', 'cssVar' => '--qiling-component-nav-hover-bg', 'group' => 'desktop_nav', 'label' => __( '桌面导航悬停背景', 'developer-starter' ) ),
            array( 'key' => 'nav_hover_text', 'cssVar' => '--qiling-component-nav-hover-text', 'group' => 'desktop_nav', 'label' => __( '桌面导航悬停文字', 'developer-starter' ) ),
            array( 'key' => 'nav_scrolled_hover_text', 'cssVar' => '--qiling-component-nav-scrolled-hover-text', 'group' => 'desktop_nav', 'label' => __( '滚动后桌面导航悬停文字', 'developer-starter' ) ),
            array( 'key' => 'mobile_nav_bg', 'cssVar' => '--qiling-component-mobile-nav-bg', 'group' => 'mobile_nav', 'label' => __( '移动导航背景', 'developer-starter' ) ),
            array( 'key' => 'mobile_nav_border', 'cssVar' => '--qiling-component-mobile-nav-border', 'group' => 'mobile_nav', 'label' => __( '移动导航边框', 'developer-starter' ) ),
            array( 'key' => 'mobile_nav_link', 'cssVar' => '--qiling-component-mobile-nav-link', 'group' => 'mobile_nav', 'label' => __( '移动导航文字', 'developer-starter' ) ),
            array( 'key' => 'mobile_nav_hover_bg', 'cssVar' => '--qiling-component-mobile-nav-hover-bg', 'group' => 'mobile_nav', 'label' => __( '移动导航悬停背景', 'developer-starter' ) ),
            array( 'key' => 'mobile_nav_hover_text', 'cssVar' => '--qiling-component-mobile-nav-hover-text', 'group' => 'mobile_nav', 'label' => __( '移动导航悬停文字', 'developer-starter' ) ),
            array( 'key' => 'dropdown_bg', 'cssVar' => '--qiling-component-dropdown-bg', 'group' => 'dropdown', 'label' => __( '下拉层背景', 'developer-starter' ) ),
            array( 'key' => 'dropdown_border', 'cssVar' => '--qiling-component-dropdown-border', 'group' => 'dropdown', 'label' => __( '下拉层边框', 'developer-starter' ) ),
            array( 'key' => 'dropdown_shadow', 'cssVar' => '--qiling-component-dropdown-shadow', 'group' => 'dropdown', 'label' => __( '下拉层阴影', 'developer-starter' ) ),
            array( 'key' => 'dropdown_link', 'cssVar' => '--qiling-component-dropdown-link', 'group' => 'dropdown', 'label' => __( '下拉层文字', 'developer-starter' ) ),
            array( 'key' => 'dropdown_hover_bg', 'cssVar' => '--qiling-component-dropdown-hover-bg', 'group' => 'dropdown', 'label' => __( '下拉层悬停背景', 'developer-starter' ) ),
            array( 'key' => 'dropdown_hover_text', 'cssVar' => '--qiling-component-dropdown-hover-text', 'group' => 'dropdown', 'label' => __( '下拉层悬停文字', 'developer-starter' ) ),
            array( 'key' => 'badge_bg', 'cssVar' => '--qiling-component-badge-bg', 'group' => 'badge', 'label' => __( '徽标背景', 'developer-starter' ) ),
            array( 'key' => 'badge_text', 'cssVar' => '--qiling-component-badge-text', 'group' => 'badge', 'label' => __( '徽标文字', 'developer-starter' ) ),
            array( 'key' => 'badge_border', 'cssVar' => '--qiling-component-badge-border', 'group' => 'badge', 'label' => __( '徽标边框', 'developer-starter' ) ),
            array( 'key' => 'tabs_border', 'cssVar' => '--qiling-component-tabs-border', 'group' => 'tabs', 'label' => __( '标签页边框', 'developer-starter' ) ),
            array( 'key' => 'tabs_text', 'cssVar' => '--qiling-component-tabs-text', 'group' => 'tabs', 'label' => __( '标签页文字', 'developer-starter' ) ),
            array( 'key' => 'tabs_active_bg', 'cssVar' => '--qiling-component-tabs-active-bg', 'group' => 'tabs', 'label' => __( '标签页激活背景', 'developer-starter' ) ),
            array( 'key' => 'tabs_active_text', 'cssVar' => '--qiling-component-tabs-active-text', 'group' => 'tabs', 'label' => __( '标签页激活文字', 'developer-starter' ) ),
            array( 'key' => 'tabs_active_border', 'cssVar' => '--qiling-component-tabs-active-border', 'group' => 'tabs', 'label' => __( '标签页激活边框', 'developer-starter' ) ),
            array( 'key' => 'accordion_bg', 'cssVar' => '--qiling-component-accordion-bg', 'group' => 'accordion', 'label' => __( '折叠面板背景', 'developer-starter' ) ),
            array( 'key' => 'accordion_border', 'cssVar' => '--qiling-component-accordion-border', 'group' => 'accordion', 'label' => __( '折叠面板边框', 'developer-starter' ) ),
            array( 'key' => 'accordion_title', 'cssVar' => '--qiling-component-accordion-title', 'group' => 'accordion', 'label' => __( '折叠面板标题', 'developer-starter' ) ),
            array( 'key' => 'pagination_bg', 'cssVar' => '--qiling-component-pagination-bg', 'group' => 'pagination', 'label' => __( '分页背景', 'developer-starter' ) ),
            array( 'key' => 'pagination_border', 'cssVar' => '--qiling-component-pagination-border', 'group' => 'pagination', 'label' => __( '分页边框', 'developer-starter' ) ),
            array( 'key' => 'pagination_text', 'cssVar' => '--qiling-component-pagination-text', 'group' => 'pagination', 'label' => __( '分页文字', 'developer-starter' ) ),
            array( 'key' => 'pagination_active_bg', 'cssVar' => '--qiling-component-pagination-active-bg', 'group' => 'pagination', 'label' => __( '分页激活背景', 'developer-starter' ) ),
            array( 'key' => 'pagination_active_text', 'cssVar' => '--qiling-component-pagination-active-text', 'group' => 'pagination', 'label' => __( '分页激活文字', 'developer-starter' ) ),
            array( 'key' => 'breadcrumb_bg', 'cssVar' => '--qiling-component-breadcrumb-bg', 'group' => 'breadcrumb', 'label' => __( '面包屑背景', 'developer-starter' ) ),
            array( 'key' => 'breadcrumb_text', 'cssVar' => '--qiling-component-breadcrumb-text', 'group' => 'breadcrumb', 'label' => __( '面包屑文字', 'developer-starter' ) ),
            array( 'key' => 'breadcrumb_link', 'cssVar' => '--qiling-component-breadcrumb-link', 'group' => 'breadcrumb', 'label' => __( '面包屑链接', 'developer-starter' ) ),
            array( 'key' => 'alert_bg', 'cssVar' => '--qiling-component-alert-bg', 'group' => 'alert', 'label' => __( '提示背景', 'developer-starter' ) ),
            array( 'key' => 'alert_border', 'cssVar' => '--qiling-component-alert-border', 'group' => 'alert', 'label' => __( '提示边框', 'developer-starter' ) ),
            array( 'key' => 'alert_text', 'cssVar' => '--qiling-component-alert-text', 'group' => 'alert', 'label' => __( '提示文字', 'developer-starter' ) ),
            array( 'key' => 'modal_bg', 'cssVar' => '--qiling-component-modal-bg', 'group' => 'modal', 'label' => __( '弹窗背景', 'developer-starter' ) ),
            array( 'key' => 'modal_border', 'cssVar' => '--qiling-component-modal-border', 'group' => 'modal', 'label' => __( '弹窗边框', 'developer-starter' ) ),
            array( 'key' => 'modal_shadow', 'cssVar' => '--qiling-component-modal-shadow', 'group' => 'modal', 'label' => __( '弹窗阴影', 'developer-starter' ) ),
            array( 'key' => 'modal_title', 'cssVar' => '--qiling-component-modal-title', 'group' => 'modal', 'label' => __( '弹窗标题', 'developer-starter' ) ),
            array( 'key' => 'announcement_marketing_bg', 'cssVar' => '--qiling-announcement-marketing-bg', 'group' => 'modal', 'label' => __( '营销公告背景', 'developer-starter' ) ),
            array( 'key' => 'announcement_marketing_button_text', 'cssVar' => '--qiling-announcement-marketing-button-text', 'group' => 'modal', 'label' => __( '营销公告按钮文字', 'developer-starter' ) ),
            array( 'key' => 'sidebar_bg', 'cssVar' => '--qiling-component-sidebar-bg', 'group' => 'sidebar', 'label' => __( '侧栏背景', 'developer-starter' ) ),
            array( 'key' => 'sidebar_border', 'cssVar' => '--qiling-component-sidebar-border', 'group' => 'sidebar', 'label' => __( '侧栏边框', 'developer-starter' ) ),
            array( 'key' => 'sidebar_shadow', 'cssVar' => '--qiling-component-sidebar-shadow', 'group' => 'sidebar', 'label' => __( '侧栏阴影', 'developer-starter' ) ),
            array( 'key' => 'sidebar_title', 'cssVar' => '--qiling-component-sidebar-title', 'group' => 'sidebar', 'label' => __( '侧栏标题', 'developer-starter' ) ),
            array( 'key' => 'footer_bg', 'cssVar' => '--qiling-component-footer-bg', 'group' => 'footer', 'label' => __( '页脚主背景', 'developer-starter' ) ),
            array( 'key' => 'footer_text', 'cssVar' => '--qiling-component-footer-text', 'group' => 'footer', 'label' => __( '页脚文字', 'developer-starter' ) ),
            array( 'key' => 'footer_heading', 'cssVar' => '--qiling-component-footer-heading', 'group' => 'footer', 'label' => __( '页脚标题', 'developer-starter' ) ),
            array( 'key' => 'footer_heading_size', 'cssVar' => '--qiling-component-footer-heading-size', 'group' => 'footer', 'label' => __( '页脚标题字号', 'developer-starter' ) ),
            array( 'key' => 'footer_link', 'cssVar' => '--qiling-component-footer-link', 'group' => 'footer', 'label' => __( '页脚链接', 'developer-starter' ) ),
            array( 'key' => 'footer_link_hover', 'cssVar' => '--qiling-component-footer-link-hover', 'group' => 'footer', 'label' => __( '页脚链接悬停', 'developer-starter' ) ),
            array( 'key' => 'footer_bottom_bg', 'cssVar' => '--qiling-component-footer-bottom-bg', 'group' => 'footer', 'label' => __( '页脚底栏背景', 'developer-starter' ) ),
            array( 'key' => 'woo_card_bg', 'cssVar' => '--qiling-component-woo-card-bg', 'group' => 'woo_card', 'label' => __( 'Woo 卡片背景', 'developer-starter' ) ),
            array( 'key' => 'woo_card_border', 'cssVar' => '--qiling-component-woo-card-border', 'group' => 'woo_card', 'label' => __( 'Woo 卡片边框', 'developer-starter' ) ),
            array( 'key' => 'woo_card_shadow', 'cssVar' => '--qiling-component-woo-card-shadow', 'group' => 'woo_card', 'label' => __( 'Woo 卡片阴影', 'developer-starter' ) ),
            array( 'key' => 'woo_card_title', 'cssVar' => '--qiling-component-woo-card-title', 'group' => 'woo_card', 'label' => __( 'Woo 卡片标题', 'developer-starter' ) ),
            array( 'key' => 'woo_card_price', 'cssVar' => '--qiling-component-woo-card-price', 'group' => 'woo_card', 'label' => __( 'Woo 价格文字', 'developer-starter' ) ),
        );
