<?php
/**
 * Data config for design component schema.
 *
 * @package Developer_Starter
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
            'button_bg'            => 'paint',
            'button_text'          => 'color',
            'button_border'        => 'color',
            'button_hover_bg'      => 'paint',
            'button_hover_text'    => 'color',
            'button_shadow'        => 'shadow',
            'button_padding'       => 'box_spacing',
            'button_secondary_bg'  => 'paint',
            'button_secondary_text' => 'color',
            'button_secondary_border' => 'color',
            'button_secondary_hover_bg' => 'paint',
            'border_accent'        => 'color',
            'heading_weight'       => 'heading_weight',
            'heading_letter_spacing' => 'box_spacing_single',
            'card_bg'              => 'paint',
            'card_border'          => 'color',
            'card_shadow'          => 'shadow',
            'title_bar_bg'         => 'paint',
            'title_bar_text'       => 'color',
            'title_bar_border'     => 'color',
            'list_header_bg'       => 'paint',
            'list_header_text'     => 'color',
            'list_header_border'   => 'color',
            'highlight_bg'         => 'paint',
            'highlight_text'       => 'color',
            'highlight_border'     => 'color',
            'highlight_soft_bg'    => 'paint',
            'form_input_bg'        => 'paint',
            'form_input_text'      => 'color',
            'form_input_border'    => 'color',
            'form_focus_border'    => 'color',
            'auth_action_bg'       => 'paint',
            'auth_action_text'     => 'color',
            'auth_code_bg'         => 'paint',
            'auth_code_text'       => 'color',
            'auth_slider_track_bg' => 'paint',
            'auth_slider_handle_bg' => 'paint',
            'auth_slider_progress_bg' => 'paint',
            'auth_verified_color'  => 'color',
            'module_title_color'   => 'color',
            'module_title_size'    => 'length',
            'module_title_align'   => 'align',
            'post_card_bg'         => 'paint',
            'post_card_border'     => 'color',
            'post_card_shadow'     => 'shadow',
            'post_card_title_color' => 'color',
            'post_card_meta_color'  => 'color',
            'header_bg'            => 'paint',
            'header_border'        => 'color',
            'header_shadow'        => 'shadow',
            'header_text'          => 'color',
            'header_scrolled_text' => 'color',
            'header_logo_transparent_fill' => 'paint',
            'header_logo_scrolled_fill' => 'paint',
            'header_phone_bg'      => 'paint',
            'header_phone_text'    => 'color',
            'header_phone_transparent_bg' => 'paint',
            'header_phone_transparent_text' => 'color',
            'nav_link'             => 'color',
            'nav_scrolled_link'    => 'color',
            'nav_hover_bg'         => 'paint',
            'nav_hover_text'       => 'color',
            'nav_scrolled_hover_text' => 'color',
            'mobile_nav_bg'        => 'paint',
            'mobile_nav_border'    => 'color',
            'mobile_nav_link'      => 'color',
            'mobile_nav_hover_bg'  => 'paint',
            'mobile_nav_hover_text'=> 'color',
            'dropdown_bg'          => 'paint',
            'dropdown_border'      => 'color',
            'dropdown_shadow'      => 'shadow',
            'dropdown_link'        => 'color',
            'dropdown_hover_bg'    => 'paint',
            'dropdown_hover_text'  => 'color',
            'badge_bg'             => 'paint',
            'badge_text'           => 'color',
            'badge_border'         => 'color',
            'tabs_border'          => 'color',
            'tabs_text'            => 'color',
            'tabs_active_bg'       => 'paint',
            'tabs_active_text'     => 'color',
            'tabs_active_border'   => 'color',
            'accordion_bg'         => 'paint',
            'accordion_border'     => 'color',
            'accordion_title'      => 'color',
            'pagination_bg'        => 'paint',
            'pagination_border'    => 'color',
            'pagination_text'      => 'color',
            'pagination_active_bg' => 'paint',
            'pagination_active_text' => 'color',
            'breadcrumb_bg'        => 'paint',
            'breadcrumb_text'      => 'color',
            'breadcrumb_link'      => 'color',
            'alert_bg'             => 'paint',
            'alert_border'         => 'color',
            'alert_text'           => 'color',
            'modal_bg'             => 'paint',
            'modal_border'         => 'color',
            'modal_shadow'         => 'shadow',
            'modal_title'          => 'color',
            'announcement_marketing_bg' => 'paint',
            'announcement_marketing_button_text' => 'color',
            'sidebar_bg'           => 'paint',
            'sidebar_border'       => 'color',
            'sidebar_shadow'       => 'shadow',
            'sidebar_title'        => 'color',
            'footer_bg'            => 'paint',
            'footer_text'          => 'color',
            'footer_heading'       => 'color',
            'footer_heading_size'  => 'length',
            'footer_link'          => 'color',
            'footer_link_hover'    => 'color',
            'footer_bottom_bg'     => 'paint',
            'woo_card_bg'          => 'paint',
            'woo_card_border'      => 'color',
            'woo_card_shadow'      => 'shadow',
            'woo_card_title'       => 'color',
            'woo_card_price'       => 'color',
        );
