<?php
/**
 * Data config for design component option map.
 *
 * @package Developer_Starter
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
            'design_component_button_bg'         => 'button_bg',
            'design_component_button_text'       => 'button_text',
            'design_component_button_border'     => 'button_border',
            'design_component_button_hover_bg'   => 'button_hover_bg',
            'design_component_button_hover_text' => 'button_hover_text',
            'design_component_button_secondary_bg' => 'button_secondary_bg',
            'design_component_button_secondary_text' => 'button_secondary_text',
            'design_component_button_secondary_border' => 'button_secondary_border',
            'design_component_button_secondary_hover_bg' => 'button_secondary_hover_bg',
            'design_component_border_accent'    => 'border_accent',
            'design_component_button_shadow'     => 'button_shadow',
            'design_component_button_padding'    => 'button_padding',
            'design_component_heading_weight'    => 'heading_weight',
            'design_component_heading_letter_spacing' => 'heading_letter_spacing',
            'design_component_card_bg'           => 'card_bg',
            'design_component_card_border'       => 'card_border',
            'design_component_card_shadow'       => 'card_shadow',
            'design_component_title_bar_bg'      => 'title_bar_bg',
            'design_component_title_bar_text'    => 'title_bar_text',
            'design_component_title_bar_border'  => 'title_bar_border',
            'design_component_list_header_bg'    => 'list_header_bg',
            'design_component_list_header_text'  => 'list_header_text',
            'design_component_list_header_border'=> 'list_header_border',
            'design_component_highlight_bg'      => 'highlight_bg',
            'design_component_highlight_text'    => 'highlight_text',
            'design_component_highlight_border'  => 'highlight_border',
            'design_component_highlight_soft_bg' => 'highlight_soft_bg',
            'design_component_form_input_bg'     => 'form_input_bg',
            'design_component_form_input_text'   => 'form_input_text',
            'design_component_form_input_border' => 'form_input_border',
            'design_component_form_focus_border' => 'form_focus_border',
            'design_component_auth_action_bg'    => 'auth_action_bg',
            'design_component_auth_action_text'  => 'auth_action_text',
            'design_component_auth_code_bg'      => 'auth_code_bg',
            'design_component_auth_code_text'    => 'auth_code_text',
            'design_component_auth_slider_track_bg' => 'auth_slider_track_bg',
            'design_component_auth_slider_handle_bg' => 'auth_slider_handle_bg',
            'design_component_auth_slider_progress_bg' => 'auth_slider_progress_bg',
            'design_component_auth_verified_color' => 'auth_verified_color',
            'design_component_module_title_color' => 'module_title_color',
            'design_component_module_title_size'  => 'module_title_size',
            'design_component_module_title_align' => 'module_title_align',
            'design_component_post_card_bg'       => 'post_card_bg',
            'design_component_post_card_border'   => 'post_card_border',
            'design_component_post_card_shadow'   => 'post_card_shadow',
            'design_component_post_card_title_color' => 'post_card_title_color',
            'design_component_post_card_meta_color'  => 'post_card_meta_color',
            'design_component_header_bg'          => 'header_bg',
            'design_component_header_border'      => 'header_border',
            'design_component_header_shadow'      => 'header_shadow',
            'design_component_header_text'        => 'header_text',
            'design_component_header_scrolled_text' => 'header_scrolled_text',
            'design_component_header_logo_transparent_fill' => 'header_logo_transparent_fill',
            'design_component_header_logo_scrolled_fill' => 'header_logo_scrolled_fill',
            'design_component_header_phone_bg'    => 'header_phone_bg',
            'design_component_header_phone_text'  => 'header_phone_text',
            'design_component_header_phone_transparent_bg' => 'header_phone_transparent_bg',
            'design_component_header_phone_transparent_text' => 'header_phone_transparent_text',
            'design_component_nav_link'           => 'nav_link',
            'design_component_nav_scrolled_link'  => 'nav_scrolled_link',
            'design_component_nav_hover_bg'       => 'nav_hover_bg',
            'design_component_nav_hover_text'     => 'nav_hover_text',
            'design_component_nav_scrolled_hover_text' => 'nav_scrolled_hover_text',
            'design_component_mobile_nav_bg'      => 'mobile_nav_bg',
            'design_component_mobile_nav_border'  => 'mobile_nav_border',
            'design_component_mobile_nav_link'    => 'mobile_nav_link',
            'design_component_mobile_nav_hover_bg' => 'mobile_nav_hover_bg',
            'design_component_mobile_nav_hover_text' => 'mobile_nav_hover_text',
            'design_component_dropdown_bg'        => 'dropdown_bg',
            'design_component_dropdown_border'    => 'dropdown_border',
            'design_component_dropdown_shadow'    => 'dropdown_shadow',
            'design_component_dropdown_link'      => 'dropdown_link',
            'design_component_dropdown_hover_bg'  => 'dropdown_hover_bg',
            'design_component_dropdown_hover_text' => 'dropdown_hover_text',
            'design_component_badge_bg'           => 'badge_bg',
            'design_component_badge_text'         => 'badge_text',
            'design_component_badge_border'       => 'badge_border',
            'design_component_tabs_border'        => 'tabs_border',
            'design_component_tabs_text'          => 'tabs_text',
            'design_component_tabs_active_bg'     => 'tabs_active_bg',
            'design_component_tabs_active_text'   => 'tabs_active_text',
            'design_component_tabs_active_border' => 'tabs_active_border',
            'design_component_accordion_bg'       => 'accordion_bg',
            'design_component_accordion_border'   => 'accordion_border',
            'design_component_accordion_title'    => 'accordion_title',
            'design_component_pagination_bg'      => 'pagination_bg',
            'design_component_pagination_border'  => 'pagination_border',
            'design_component_pagination_text'    => 'pagination_text',
            'design_component_pagination_active_bg' => 'pagination_active_bg',
            'design_component_pagination_active_text' => 'pagination_active_text',
            'design_component_breadcrumb_bg'      => 'breadcrumb_bg',
            'design_component_breadcrumb_text'    => 'breadcrumb_text',
            'design_component_breadcrumb_link'    => 'breadcrumb_link',
            'design_component_alert_bg'           => 'alert_bg',
            'design_component_alert_border'       => 'alert_border',
            'design_component_alert_text'         => 'alert_text',
            'design_component_modal_bg'           => 'modal_bg',
            'design_component_modal_border'       => 'modal_border',
            'design_component_modal_shadow'       => 'modal_shadow',
            'design_component_modal_title'        => 'modal_title',
            'design_component_announcement_marketing_bg' => 'announcement_marketing_bg',
            'design_component_announcement_marketing_button_text' => 'announcement_marketing_button_text',
            'design_component_sidebar_bg'         => 'sidebar_bg',
            'design_component_sidebar_border'     => 'sidebar_border',
            'design_component_sidebar_shadow'     => 'sidebar_shadow',
            'design_component_sidebar_title'      => 'sidebar_title',
            'design_component_footer_bg'          => 'footer_bg',
            'design_component_footer_text'        => 'footer_text',
            'design_component_footer_heading'     => 'footer_heading',
            'design_component_footer_heading_size' => 'footer_heading_size',
            'design_component_footer_link'        => 'footer_link',
            'design_component_footer_link_hover'  => 'footer_link_hover',
            'design_component_footer_bottom_bg'   => 'footer_bottom_bg',
            'design_component_woo_card_bg'        => 'woo_card_bg',
            'design_component_woo_card_border'    => 'woo_card_border',
            'design_component_woo_card_shadow'    => 'woo_card_shadow',
            'design_component_woo_card_title'     => 'woo_card_title',
            'design_component_woo_card_price'     => 'woo_card_price',
        );
