<?php
/**
 * Data config for system style presets.
 *
 * @package Developer_Starter
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$neutral_slate = array(
	'neutral_0'   => '#ffffff',
	'neutral_50'  => '#f8fafc',
	'neutral_100' => '#f1f5f9',
	'neutral_200' => '#e2e8f0',
	'neutral_300' => '#cbd5e1',
	'neutral_400' => '#94a3b8',
	'neutral_500' => '#64748b',
	'neutral_600' => '#475569',
	'neutral_700' => '#334155',
	'neutral_800' => '#1e293b',
	'neutral_900' => '#0f172a',
);

$neutral_warm = array(
	'neutral_0'   => '#fffdf9',
	'neutral_50'  => '#faf7f2',
	'neutral_100' => '#f5eee5',
	'neutral_200' => '#ead8c4',
	'neutral_300' => '#d8b99a',
	'neutral_400' => '#bd926f',
	'neutral_500' => '#986f52',
	'neutral_600' => '#76553f',
	'neutral_700' => '#5c4232',
	'neutral_800' => '#3f2d24',
	'neutral_900' => '#241915',
);

$transparent_header_defaults = array(
	'header_logo_transparent_fill'  => '#ffffff',
	'header_phone_transparent_bg'   => 'rgba(255, 255, 255, 0.18)',
	'header_phone_transparent_text' => '#ffffff',
);

return array(
	'default'    => array(
		'label'            => __( '通用官网', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#2563eb',
				'primary_hover'   => '#1d4ed8',
				'secondary'       => '#0f766e',
				'accent'          => '#059669',
				'success'         => '#16a34a',
				'info'            => '#0ea5e9',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(15, 23, 42, 0.68)',
				'text'            => '#1f2937',
				'text_muted'      => '#64748b',
				'heading'         => '#111827',
				'background'      => '#ffffff',
				'surface'         => '#ffffff',
				'surface_alt'     => '#f8fafc',
				'border'          => '#e5e7eb',
				'dark_bg'         => '#111827',
				'dark_surface'    => '#1f2937',
				'dark_text'       => '#f3f4f6',
				'dark_text_muted' => '#cbd5e1',
				'dark_border'     => '#334155',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#2563eb',
				'button_border'                      => '#2563eb',
				'button_hover_bg'                    => '#1d4ed8',
				'button_secondary_bg'                => '#f8fafc',
				'button_secondary_text'              => '#1e293b',
				'button_secondary_border'            => '#dbe3ef',
				'button_secondary_hover_bg'          => '#eef2ff',
				'border_accent'                      => '#2563eb',
				'title_bar_bg'                       => '#eff6ff',
				'title_bar_border'                   => '#bfdbfe',
				'highlight_bg'                       => 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
				'highlight_soft_bg'                  => '#eff6ff',
				'form_focus_border'                  => '#2563eb',
				'auth_action_bg'                     => 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #059669 0%, #047857 100%)',
				'badge_bg'                           => 'linear-gradient(135deg, #059669 0%, #047857 100%)',
				'badge_border'                       => '#059669',
				'tabs_active_bg'                     => '#eff6ff',
				'tabs_active_text'                   => '#1d4ed8',
				'tabs_active_border'                 => '#2563eb',
				'alert_bg'                           => '#fff1f2',
				'alert_border'                       => '#fecdd3',
				'alert_text'                         => '#991b1b',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #2563eb 0%, #059669 100%)',
				'announcement_marketing_button_text' => '#1d4ed8',
				'footer_bg'                          => '#0f172a',
				'footer_bottom_bg'                   => '#020617',
				'woo_card_price'                     => '#059669',
			)
		),
	),
	'enterprise' => array(
		'label'            => __( '企业服务', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#1d4ed8',
				'primary_hover'   => '#1e40af',
				'secondary'       => '#0f766e',
				'accent'          => '#059669',
				'success'         => '#16a34a',
				'info'            => '#0284c7',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(15, 23, 42, 0.7)',
				'text'            => '#172033',
				'text_muted'      => '#64748b',
				'heading'         => '#0f172a',
				'background'      => '#ffffff',
				'surface'         => '#ffffff',
				'surface_alt'     => '#f1f5f9',
				'border'          => '#dbe3ef',
				'dark_bg'         => '#101828',
				'dark_surface'    => '#1d2939',
				'dark_text'       => '#f8fafc',
				'dark_text_muted' => '#cbd5e1',
				'dark_border'     => '#344054',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#1d4ed8',
				'button_border'                      => '#1d4ed8',
				'button_hover_bg'                    => '#1e40af',
				'button_secondary_bg'                => '#f8fafc',
				'button_secondary_text'              => '#0f172a',
				'button_secondary_border'            => '#dbe3ef',
				'button_secondary_hover_bg'          => '#e0f2fe',
				'border_accent'                      => '#1d4ed8',
				'title_bar_bg'                       => '#eff6ff',
				'title_bar_border'                   => '#bfdbfe',
				'highlight_bg'                       => 'linear-gradient(135deg, #1d4ed8 0%, #0f766e 100%)',
				'highlight_soft_bg'                  => '#eff6ff',
				'form_focus_border'                  => '#1d4ed8',
				'auth_action_bg'                     => 'linear-gradient(135deg, #1d4ed8 0%, #1e40af 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #0f766e 0%, #115e59 100%)',
				'badge_bg'                           => '#059669',
				'badge_border'                       => '#059669',
				'tabs_active_bg'                     => '#eff6ff',
				'tabs_active_text'                   => '#1e40af',
				'tabs_active_border'                 => '#1d4ed8',
				'alert_bg'                           => '#eff6ff',
				'alert_border'                       => '#bfdbfe',
				'alert_text'                         => '#1e3a8a',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
				'announcement_marketing_button_text' => '#1d4ed8',
				'footer_bg'                          => '#111827',
				'footer_bottom_bg'                   => '#030712',
				'woo_card_price'                     => '#1d4ed8',
			)
		),
	),
	'technology' => array(
		'label'            => __( '科技产品', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#0891b2',
				'primary_hover'   => '#0e7490',
				'secondary'       => '#059669',
				'accent'          => '#22d3ee',
				'success'         => '#10b981',
				'info'            => '#38bdf8',
				'warning'         => '#f59e0b',
				'error'           => '#f43f5e',
				'overlay'         => 'rgba(8, 15, 32, 0.72)',
				'text'            => '#102a43',
				'text_muted'      => '#627d98',
				'heading'         => '#0b172a',
				'background'      => '#ffffff',
				'surface'         => '#f8fafc',
				'surface_alt'     => '#ecfeff',
				'border'          => '#cbd5e1',
				'dark_bg'         => '#0b172a',
				'dark_surface'    => '#16324f',
				'dark_text'       => '#eef8ff',
				'dark_text_muted' => '#b6d3e6',
				'dark_border'     => '#29506d',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#0891b2',
				'button_border'                      => '#0891b2',
				'button_hover_bg'                    => '#0e7490',
				'button_secondary_bg'                => '#ecfeff',
				'button_secondary_text'              => '#164e63',
				'button_secondary_border'            => '#a5f3fc',
				'button_secondary_hover_bg'          => '#cffafe',
				'border_accent'                      => '#22d3ee',
				'title_bar_bg'                       => '#ecfeff',
				'title_bar_border'                   => '#a5f3fc',
				'highlight_bg'                       => 'linear-gradient(135deg, #0891b2 0%, #059669 100%)',
				'highlight_soft_bg'                  => '#ecfeff',
				'form_focus_border'                  => '#0891b2',
				'auth_action_bg'                     => 'linear-gradient(135deg, #0891b2 0%, #059669 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',
				'badge_bg'                           => 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',
				'badge_border'                       => '#22d3ee',
				'tabs_active_bg'                     => '#ecfeff',
				'tabs_active_text'                   => '#0e7490',
				'tabs_active_border'                 => '#0891b2',
				'alert_bg'                           => '#ecfeff',
				'alert_border'                       => '#a5f3fc',
				'alert_text'                         => '#155e75',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
				'announcement_marketing_button_text' => '#0891b2',
				'footer_bg'                          => '#0b172a',
				'footer_bottom_bg'                   => '#050b16',
				'woo_card_price'                     => '#0891b2',
			)
		),
	),
	'medical'    => array(
		'label'            => __( '医疗健康', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#0f766e',
				'primary_hover'   => '#115e59',
				'secondary'       => '#0ea5e9',
				'accent'          => '#22c55e',
				'success'         => '#16a34a',
				'info'            => '#0ea5e9',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(7, 45, 43, 0.66)',
				'text'            => '#1f2937',
				'text_muted'      => '#64748b',
				'heading'         => '#134e4a',
				'background'      => '#ffffff',
				'surface'         => '#ffffff',
				'surface_alt'     => '#ecfdf5',
				'border'          => '#ccfbf1',
				'dark_bg'         => '#0f1f1d',
				'dark_surface'    => '#153532',
				'dark_text'       => '#f0fdfa',
				'dark_text_muted' => '#99f6e4',
				'dark_border'     => '#2dd4bf',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#0f766e',
				'button_border'                      => '#0f766e',
				'button_hover_bg'                    => '#115e59',
				'button_secondary_bg'                => '#ecfdf5',
				'button_secondary_text'              => '#134e4a',
				'button_secondary_border'            => '#99f6e4',
				'button_secondary_hover_bg'          => '#ccfbf1',
				'border_accent'                      => '#0f766e',
				'title_bar_bg'                       => '#ecfdf5',
				'title_bar_border'                   => '#99f6e4',
				'highlight_bg'                       => 'linear-gradient(135deg, #0f766e 0%, #0ea5e9 100%)',
				'highlight_soft_bg'                  => '#ecfdf5',
				'form_focus_border'                  => '#0f766e',
				'auth_action_bg'                     => 'linear-gradient(135deg, #0f766e 0%, #115e59 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
				'badge_bg'                           => '#22c55e',
				'badge_border'                       => '#22c55e',
				'tabs_active_bg'                     => '#ecfdf5',
				'tabs_active_text'                   => '#0f766e',
				'tabs_active_border'                 => '#0f766e',
				'alert_bg'                           => '#ecfdf5',
				'alert_border'                       => '#99f6e4',
				'alert_text'                         => '#14532d',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #14b8a6 0%, #0f766e 100%)',
				'announcement_marketing_button_text' => '#0f766e',
				'footer_bg'                          => '#0f1f1d',
				'footer_bottom_bg'                   => '#07110f',
				'woo_card_price'                     => '#0f766e',
			)
		),
	),
	'education'  => array(
		'label'            => __( '教育培训', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#2563eb',
				'primary_hover'   => '#1d4ed8',
				'secondary'       => '#0f766e',
				'accent'          => '#059669',
				'success'         => '#16a34a',
				'info'            => '#2563eb',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(30, 27, 75, 0.68)',
				'text'            => '#1e293b',
				'text_muted'      => '#64748b',
				'heading'         => '#0f172a',
				'background'      => '#ffffff',
				'surface'         => '#ffffff',
				'surface_alt'     => '#fffbeb',
				'border'          => '#fde68a',
				'dark_bg'         => '#111827',
				'dark_surface'    => '#1f2937',
				'dark_text'       => '#f9fafb',
				'dark_text_muted' => '#d1d5db',
				'dark_border'     => '#475569',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#2563eb',
				'button_border'                      => '#2563eb',
				'button_hover_bg'                    => '#1d4ed8',
				'button_secondary_bg'                => '#fffbeb',
				'button_secondary_text'              => '#713f12',
				'button_secondary_border'            => '#fde68a',
				'button_secondary_hover_bg'          => '#fef3c7',
				'border_accent'                      => '#059669',
				'title_bar_bg'                       => '#eef2ff',
				'title_bar_border'                   => '#c7d2fe',
				'highlight_bg'                       => 'linear-gradient(135deg, #2563eb 0%, #0f766e 100%)',
				'highlight_soft_bg'                  => '#eef2ff',
				'form_focus_border'                  => '#2563eb',
				'auth_action_bg'                     => 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #059669 0%, #047857 100%)',
				'badge_bg'                           => '#059669',
				'badge_border'                       => '#059669',
				'tabs_active_bg'                     => '#eef2ff',
				'tabs_active_text'                   => '#1d4ed8',
				'tabs_active_border'                 => '#2563eb',
				'alert_bg'                           => '#fffbeb',
				'alert_border'                       => '#fde68a',
				'alert_text'                         => '#713f12',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #2563eb 0%, #059669 100%)',
				'announcement_marketing_button_text' => '#1d4ed8',
				'footer_bg'                          => '#172554',
				'footer_bottom_bg'                   => '#0f172a',
				'woo_card_price'                     => '#2563eb',
			)
		),
	),
	'restaurant' => array(
		'label'            => __( '餐饮门店', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_warm,
			array(
				'primary'         => '#059669',
				'primary_hover'   => '#047857',
				'secondary'       => '#2563eb',
				'accent'          => '#0ea5e9',
				'success'         => '#16a34a',
				'info'            => '#0284c7',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(69, 26, 3, 0.68)',
				'text'            => '#2f241f',
				'text_muted'      => '#76553f',
				'heading'         => '#241915',
				'background'      => '#fffdf9',
				'surface'         => '#ffffff',
				'surface_alt'     => '#fff7ed',
				'border'          => '#fed7aa',
				'dark_bg'         => '#1f1313',
				'dark_surface'    => '#331c1c',
				'dark_text'       => '#fff7ed',
				'dark_text_muted' => '#fed7aa',
				'dark_border'     => '#7f1d1d',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#059669',
				'button_border'                      => '#059669',
				'button_hover_bg'                    => '#047857',
				'button_secondary_bg'                => '#fff7ed',
				'button_secondary_text'              => '#9a3412',
				'button_secondary_border'            => '#fed7aa',
				'button_secondary_hover_bg'          => '#ffedd5',
				'border_accent'                      => '#0ea5e9',
				'title_bar_bg'                       => '#fff7ed',
				'title_bar_border'                   => '#fed7aa',
				'highlight_bg'                       => 'linear-gradient(135deg, #059669 0%, #0ea5e9 100%)',
				'highlight_soft_bg'                  => '#fff7ed',
				'form_focus_border'                  => '#059669',
				'auth_action_bg'                     => 'linear-gradient(135deg, #059669 0%, #047857 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
				'badge_bg'                           => '#0ea5e9',
				'badge_border'                       => '#0ea5e9',
				'tabs_active_bg'                     => '#fff7ed',
				'tabs_active_text'                   => '#047857',
				'tabs_active_border'                 => '#059669',
				'alert_bg'                           => '#fff7ed',
				'alert_border'                       => '#fed7aa',
				'alert_text'                         => '#9a3412',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #059669 0%, #2563eb 100%)',
				'announcement_marketing_button_text' => '#047857',
				'footer_bg'                          => '#064e3b',
				'footer_bottom_bg'                   => '#022c22',
				'woo_card_price'                     => '#059669',
			)
		),
	),
	'magazine'   => array(
		'label'            => __( '杂志媒体', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#1d4ed8',
				'primary_hover'   => '#1e40af',
				'secondary'       => '#0f766e',
				'accent'          => '#059669',
				'success'         => '#16a34a',
				'info'            => '#2563eb',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(17, 24, 39, 0.7)',
				'text'            => '#1f2937',
				'text_muted'      => '#6b7280',
				'heading'         => '#0f172a',
				'background'      => '#ffffff',
				'surface'         => '#ffffff',
				'surface_alt'     => '#f9fafb',
				'border'          => '#e5e7eb',
				'dark_bg'         => '#0f172a',
				'dark_surface'    => '#1f2937',
				'dark_text'       => '#f9fafb',
				'dark_text_muted' => '#d1d5db',
				'dark_border'     => '#374151',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#1d4ed8',
				'button_border'                      => '#1d4ed8',
				'button_hover_bg'                    => '#1e40af',
				'button_secondary_bg'                => '#f9fafb',
				'button_secondary_text'              => '#111827',
				'button_secondary_border'            => '#e5e7eb',
				'button_secondary_hover_bg'          => '#f3f4f6',
				'border_accent'                      => '#059669',
				'title_bar_bg'                       => '#fff1f2',
				'title_bar_border'                   => '#fecdd3',
				'highlight_bg'                       => 'linear-gradient(135deg, #1d4ed8 0%, #059669 100%)',
				'highlight_soft_bg'                  => '#fff1f2',
				'form_focus_border'                  => '#1d4ed8',
				'auth_action_bg'                     => 'linear-gradient(135deg, #1d4ed8 0%, #1e40af 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #059669 0%, #047857 100%)',
				'badge_bg'                           => '#059669',
				'badge_border'                       => '#059669',
				'tabs_active_bg'                     => '#fff1f2',
				'tabs_active_text'                   => '#1d4ed8',
				'tabs_active_border'                 => '#1d4ed8',
				'alert_bg'                           => '#fff1f2',
				'alert_border'                       => '#fecdd3',
				'alert_text'                         => '#9f1239',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #1d4ed8 0%, #059669 100%)',
				'announcement_marketing_button_text' => '#1d4ed8',
				'footer_bg'                          => '#0f172a',
				'footer_bottom_bg'                   => '#020617',
				'woo_card_price'                     => '#059669',
			)
		),
	),
	'minimal'    => array(
		'label'            => __( '极简内容', 'developer-starter' ),
		'tokens'           => array_merge(
			$neutral_slate,
			array(
				'primary'         => '#0f766e',
				'primary_hover'   => '#115e59',
				'secondary'       => '#0ea5e9',
				'accent'          => '#14b8a6',
				'success'         => '#16a34a',
				'info'            => '#0ea5e9',
				'warning'         => '#f59e0b',
				'error'           => '#dc2626',
				'overlay'         => 'rgba(17, 24, 39, 0.64)',
				'text'            => '#1f2937',
				'text_muted'      => '#64748b',
				'heading'         => '#111827',
				'background'      => '#ffffff',
				'surface'         => '#ffffff',
				'surface_alt'     => '#f8fafc',
				'border'          => '#e5e7eb',
				'dark_bg'         => '#111827',
				'dark_surface'    => '#1f2937',
				'dark_text'       => '#f9fafb',
				'dark_text_muted' => '#cbd5e1',
				'dark_border'     => '#334155',
			)
		),
		'component_styles' => array_merge(
			$transparent_header_defaults,
			array(
				'button_bg'                          => '#0f766e',
				'button_border'                      => '#0f766e',
				'button_hover_bg'                    => '#115e59',
				'button_secondary_bg'                => '#f8fafc',
				'button_secondary_text'              => '#111827',
				'button_secondary_border'            => '#e5e7eb',
				'button_secondary_hover_bg'          => '#f1f5f9',
				'border_accent'                      => '#14b8a6',
				'title_bar_bg'                       => '#f8fafc',
				'title_bar_border'                   => '#e5e7eb',
				'highlight_bg'                       => 'linear-gradient(135deg, #0f766e 0%, #0ea5e9 100%)',
				'highlight_soft_bg'                  => '#f8fafc',
				'form_focus_border'                  => '#0f766e',
				'auth_action_bg'                     => 'linear-gradient(135deg, #0f766e 0%, #115e59 100%)',
				'auth_code_bg'                       => 'linear-gradient(135deg, #14b8a6 0%, #0f766e 100%)',
				'badge_bg'                           => '#14b8a6',
				'badge_border'                       => '#14b8a6',
				'tabs_active_bg'                     => '#f8fafc',
				'tabs_active_text'                   => '#0f766e',
				'tabs_active_border'                 => '#0f766e',
				'alert_bg'                           => '#ecfeff',
				'alert_border'                       => '#a5f3fc',
				'alert_text'                         => '#155e75',
				'announcement_marketing_bg'          => 'linear-gradient(135deg, #0ea5e9 0%, #14b8a6 100%)',
				'announcement_marketing_button_text' => '#0ea5e9',
				'footer_bg'                          => '#111827',
				'footer_bottom_bg'                   => '#030712',
				'woo_card_price'                     => '#14b8a6',
			)
		),
	),
);
